"""Capture power traces from the CW305 FPGA for MT-TMVP side-channel attack.

Acquires one trace per input combination using the ChipWhisperer platform.
Expects inputs generated by generate_inputs.py.
"""

import os
import sys
import time
import json
import shutil
import argparse
from datetime import datetime
from dataclasses import dataclass
from typing import Optional, List

import chipwhisperer as cw
import numpy as np

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("Note: Install tqdm for progress bars (pip install tqdm)")

# TMVP parameters
REAL_N = 509
BYTECNT_SIZE = 9


@dataclass
class CaptureConfig:
    """Configuration for trace capture."""
    input_dir: str = "dataset"
    output_dir: str = "dataset"
    num_samples: int = 20000
    gain_db: float = 20.0
    clock_freq: float = 7.37e6
    debug_mode: bool = False
    resume_from: int = 0  # Resume from this trace index


def setup_scope_target(config: CaptureConfig, debug: bool = False):
    """Initialize ChipWhisperer scope and CW305 target."""
    if debug:
        print("[DEBUG] Connecting to scope...")
    
    scope = cw.scopes.OpenADC()
    scope.con(idProduct=0xace2, prog_speed=int(10e6))
    
    scope.gain.db = config.gain_db
    scope.adc.basic_mode = "rising_edge"
    scope.adc.offset = 0
    scope.adc.presamples = 0
    scope.adc.samples = config.num_samples
    scope.clock.adc_src = "extclk_x1"
    scope.io.tio1 = "serial_rx"
    scope.io.tio2 = "serial_tx"
    scope.io.hs2 = "disabled"
    scope.trigger.triggers = "tio4"
    
    if debug:
        print("[DEBUG] Connecting to CW305 target...")
    
    target = cw.targets.CW305()
    target._con(scope, bsfile=None, force=False, fpga_id='100t')
    target.vccint_set(1.0)
    
    target.pll.pll_enable_set(True)
    target.pll.pll_outenable_set(False, 0)
    target.pll.pll_outenable_set(True, 1)
    target.pll.pll_outenable_set(False, 2)
    target.pll.pll_outfreq_set(config.clock_freq, 1)
    
    target.clkusbautooff = True
    target.clksleeptime = 5
    
    return scope, target


def lock_adc(scope, debug: bool = False):
    """Lock the ADC to external clock."""
    for attempt in range(5):
        scope.clock.reset_adc()
        time.sleep(1)
        if scope.clock.adc_locked:
            print("ADC locked successfully")
            return
    raise Exception("ADC failed to lock after 5 attempts")


class DutInterface:
    """Interface to the TMVP DUT on CW305."""
    
    REG_DUT_GO = 0x05
    REG_DUT_FLUSHFIFO = 0x06
    REG_DUT_RESET = 0x07
    REG_DUT_RAM_F = 0x08
    REG_DUT_RAM_G = 0x09
    REG_DUT_DATA_OUT = 0x0a
    
    def __init__(self, target, debug: bool = False):
        self.target = target
        self.target.bytecount_size = BYTECNT_SIZE
        self.debug = debug
    
    def reset_dut(self):
        """Reset the DUT and flush FIFOs."""
        self.target.bytecount_size = BYTECNT_SIZE
        self.target.fpga_write(self.REG_DUT_RESET, [0x1])
        time.sleep(0.1)
        _ = self.target.fpga_read(self.REG_DUT_DATA_OUT, REAL_N)
        self.target.fpga_write(self.REG_DUT_FLUSHFIFO, [0x1])
        time.sleep(0.1)


def do_capture_cycle(scope, dut: DutInterface, f_data: list, g_data: list,
                     capture_trace: bool = True):
    """Perform one capture cycle."""
    dut.target.bytecount_size = BYTECNT_SIZE
    
    # Write inputs
    dut.target.fpga_write(dut.REG_DUT_RAM_F, bytearray(f_data))
    dut.target.fpga_write(dut.REG_DUT_RAM_G, bytearray(g_data))
    
    # Flush FIFO
    dut.target.fpga_write(dut.REG_DUT_FLUSHFIFO, [0x1])
    time.sleep(0.02)
    
    # Trigger
    if capture_trace:
        scope.arm()
        time.sleep(0.001)
    dut.target.usb_trigger_toggle()
    
    # Wait for scope/DUT
    if capture_trace:
        if scope.capture():
            raise Exception("Scope timed out")
    
    # Wait for DUT done
    for _ in range(200):
        if dut.target.fpga_read(dut.REG_DUT_GO, 1)[0] != 0x01:
            break
        time.sleep(0.005)
    else:
        raise Exception("DUT did not complete in time")
    
    # Read output
    actual_output = list(dut.target.fpga_read(dut.REG_DUT_DATA_OUT, REAL_N))
    
    # Get trace
    wave = None
    if capture_trace:
        wave = scope.get_last_trace()
        if len(wave) == 0:
            raise Exception("Empty trace")
    
    # Reset DUT
    dut.target.fpga_write(dut.REG_DUT_RESET, [0x1])
    time.sleep(0.02)
    
    return actual_output, wave


def save_trace(output_dir: str, trace_index: int, wave: np.ndarray,
               f_data: np.ndarray, g_data: np.ndarray, 
               computed_data: np.ndarray, labels: np.ndarray) -> str:
    """Save a single trace in the standard format."""
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f"traces_{trace_index}.npz")
    
    np.savez_compressed(
        filename,
        wave=wave.reshape(1, -1).astype(np.float64),
        dut_io_ram_f_data=np.array(f_data).reshape(1, -1).astype(np.int64),
        dut_io_ram_g_data=np.array(g_data).reshape(1, -1).astype(np.int64),
        dut_io_computed_data=np.array(computed_data).reshape(1, -1).astype(np.int64),
        labels=np.array(labels).reshape(1, -1).astype(np.int64),  # (1, 8) labels for all coefficients
        trace_index=trace_index
    )
    
    return filename


def capture_all_combinations_dataset(config: CaptureConfig):
    """
    Capture traces for ALL 3^10 = 59049 f vector combinations.
    """
    
    # Load configuration
    config_file = os.path.join(config.input_dir, "inputs", "config.json")
    if not os.path.exists(config_file):
        print(f"ERROR: Config file not found: {config_file}")
        print("Run generate_inputs_v4.py first to create inputs.")
        return
    
    with open(config_file) as f:
        input_config = json.load(f)
    
    num_combinations = input_config["num_combinations"]
    num_target_coefficients = input_config["num_target_coefficients"]
    
    print("=" * 70)
    print("MT-TMVP DL-SCA Trace Capture - ALL COMBINATIONS")
    print("=" * 70)
    print(f"\nMethodology: {input_config['methodology']}")
    print(f"Target coefficients: 0 to {num_target_coefficients - 1}")
    print(f"Total combinations: {num_combinations}")
    print(f"\nInput directory: {config.input_dir}")
    print(f"Output directory: {config.output_dir}")
    print(f"Samples per trace: {config.num_samples}")
    if config.resume_from > 0:
        print(f"Resuming from trace: {config.resume_from}")
    print("=" * 70)
    
    # Load input data
    print("\nLoading input data...")
    inputs_dir = os.path.join(config.input_dir, "inputs")
    
    all_f_data = np.load(os.path.join(inputs_dir, "all_f_combinations.npy"))
    all_g_data = np.load(os.path.join(inputs_dir, "all_g_data.npy"))
    labels = np.load(os.path.join(inputs_dir, "labels.npy"))
    expected_outputs = np.load(os.path.join(inputs_dir, "expected_outputs.npy"))
    
    print(f"  all_f_data: {all_f_data.shape}")
    print(f"  all_g_data: {all_g_data.shape}")
    print(f"  labels: {labels.shape}")
    
    # Create output directory
    os.makedirs(config.output_dir, exist_ok=True)
    traces_dir = os.path.join(config.output_dir, "traces")
    os.makedirs(traces_dir, exist_ok=True)
    
    # Copy inputs to output for reference
    output_inputs_dir = os.path.join(config.output_dir, "inputs")
    if not os.path.exists(output_inputs_dir):
        shutil.copytree(inputs_dir, output_inputs_dir)
        print(f"  Copied inputs to {output_inputs_dir}")
    
    # Save capture configuration
    capture_config_file = os.path.join(config.output_dir, "capture_config.json")
    capture_cfg = {
        "methodology": "all_combinations",
        "num_combinations": num_combinations,
        "num_target_coefficients": num_target_coefficients,
        "target_coefficients": list(range(num_target_coefficients)),
        "num_samples": config.num_samples,
        "gain_db": config.gain_db,
        "clock_freq": config.clock_freq,
        "input_dir": config.input_dir,
        "capture_start": datetime.now().isoformat(),
    }
    with open(capture_config_file, 'w') as f:
        json.dump(capture_cfg, f, indent=2)
    
    # Initialize hardware
    scope = None
    target = None
    
    try:
        print("\nConnecting to hardware...")
        scope, target = setup_scope_target(config, debug=config.debug_mode)
        lock_adc(scope, debug=config.debug_mode)
        
        dut = DutInterface(target, debug=config.debug_mode)
        dut.reset_dut()
        print("DUT initialized")
        
        # =====================================================================
        # Capture ALL traces
        # =====================================================================
        print("\n" + "=" * 70)
        print(f"CAPTURING {num_combinations} TRACES")
        print("=" * 70)
        
        total_captured = 0
        errors = 0
        
        iterator = range(config.resume_from, num_combinations)
        if HAS_TQDM:
            iterator = tqdm(iterator, desc="Capturing", unit="traces",
                           initial=config.resume_from, total=num_combinations)
        
        for i in iterator:
            f_data = list(all_f_data[i])
            g_data = list(all_g_data[i])
            trace_labels = labels[i]
            
            try:
                # Reset and prime
                dut.reset_dut()
                _, _ = do_capture_cycle(scope, dut, f_data, g_data, capture_trace=False)
                
                # Real capture
                actual_output, wave = do_capture_cycle(scope, dut, f_data, g_data, capture_trace=True)
                
                # Verify output (optional)
                expected = expected_outputs[i]
                if not np.array_equal(actual_output, expected):
                    if not HAS_TQDM:
                        print(f"\n  [WARNING] Trace {i}: Output mismatch")
                
                # Save trace
                save_trace(traces_dir, i, np.array(wave),
                          f_data, g_data, actual_output, trace_labels)
                total_captured += 1
                
            except Exception as e:
                errors += 1
                if not HAS_TQDM:
                    print(f"\n  [ERROR] Trace {i}: {e}")
                dut.reset_dut()
                time.sleep(0.5)
            
            # Periodic status update
            if not HAS_TQDM and (i + 1) % 100 == 0:
                print(f"  Progress: {i + 1}/{num_combinations} ({100*(i+1)/num_combinations:.1f}%)")
        
        # =====================================================================
        # Summary
        # =====================================================================
        print("\n" + "=" * 70)
        print("CAPTURE COMPLETE!")
        print("=" * 70)
        print(f"Total traces captured: {total_captured:,}")
        print(f"Errors: {errors}")
        print(f"Output directory: {config.output_dir}")
        
        # Update config with results
        capture_cfg["capture_end"] = datetime.now().isoformat()
        capture_cfg["total_captured"] = total_captured
        capture_cfg["errors"] = errors
        with open(capture_config_file, 'w') as f:
            json.dump(capture_cfg, f, indent=2)
        
        print("\n" + "=" * 70)
        print("DATASET STRUCTURE:")
        print("=" * 70)
        print(f"  {config.output_dir}/")
        print(f"  ├── capture_config.json")
        print(f"  ├── inputs/              (copy of input data)")
        print(f"  └── traces/")
        print(f"      ├── traces_0.npz")
        print(f"      ├── traces_1.npz")
        print(f"      └── ... ({total_captured} files)")
        
        print("\n" + "=" * 70)
        print("NEXT STEPS:")
        print("=" * 70)
        print("1. Run verify_dataset.py to verify the captured data")
        print("2. Run train_attack.py to perform the attack")
        print("   (70% train, 15% val, 15% test split)")
        print("=" * 70)
        
    finally:
        if scope:
            scope.dis()
        if target:
            target.dis()
        print("\nHardware disconnected")


def main():
    parser = argparse.ArgumentParser(
        description="Capture traces for MT-TMVP DL-SCA (All Combinations)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python capture_traces.py --input-dir dataset --output-dir dataset
  python capture_traces.py --input-dir dataset --output-dir dataset --resume-from 1000
        """
    )
    
    parser.add_argument("--input-dir", type=str, default="dataset",
                        help="Input directory with generated inputs (default: dataset)")
    parser.add_argument("--output-dir", type=str, default="dataset",
                        help="Output directory for traces (default: dataset)")
    parser.add_argument("--num-samples", type=int, default=20000,
                        help="ADC samples per trace (default: 20000)")
    parser.add_argument("--gain", type=float, default=20.0,
                        help="Scope gain in dB (default: 20.0)")
    parser.add_argument("--clock", type=float, default=7.37e6,
                        help="Target clock frequency (default: 7.37e6)")
    parser.add_argument("--resume-from", type=int, default=0,
                        help="Resume from this trace index")
    parser.add_argument("--debug", action="store_true",
                        help="Enable debug mode")
    
    args = parser.parse_args()
    
    config = CaptureConfig(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        num_samples=args.num_samples,
        gain_db=args.gain,
        clock_freq=args.clock,
        debug_mode=args.debug,
        resume_from=args.resume_from,
    )
    
    capture_all_combinations_dataset(config)


if __name__ == "__main__":
    main()
